services:
    asdoria_import.handle_resolver.base:
      class: Asdoria\SyliusImportPlugin\Resolver\HandlerResolver
      calls:
        - [ 'setLogger', ['@logger']]
        - [ 'setServiceRegistry', ['@asdoria_import.serializer_service_registry']]

    asdoria_import.handle_resolver.customer:
      parent: asdoria_import.handle_resolver.base
      tags:
        - { name: asdoria_import_handler_resolver, type: 'App\Entity\Customer\Customer' }

    asdoria_import.handle_resolver.shop_user:
      parent: asdoria_import.handle_resolver.base
      tags:
        - { name: asdoria_import_handler_resolver, type: 'App\Entity\User\ShopUser' }

    asdoria_import.handle_resolver.product_attribute:
      parent: asdoria_import.handle_resolver.base
      tags:
        - { name: asdoria_import_handler_resolver, type: 'App\Entity\Product\ProductAttribute' }

    asdoria_import.handle_resolver.product:
      parent: asdoria_import.handle_resolver.base
      tags:
        - { name: asdoria_import_handler_resolver, type: 'App\Entity\Product\Product' }

