parameters:
  asdoria_import.converter.path: "@@AsdoriaSyliusImportPlugin/Resources/config/converter/%s.yaml"

services:
    asdoria_import.serializer.abstract:
      abstract: true
      class: Asdoria\SyliusImportPlugin\Serializer\BaseSerializer
      calls:
        - [ setEntityManager, ['@doctrine.orm.default_entity_manager']]
        - [ setSerializerResolver, ['@asdoria_import.serializer_service_registry']]
        - [ setConverterPath, ['%asdoria_import.converter.path%']]
        - [ setKernel, ['@kernel']]

    asdoria_import.serializer.customer:
      class: Asdoria\SyliusImportPlugin\Serializer\CustomerSerializer
      parent: asdoria_import.serializer.abstract
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Customer\Customer' }

    asdoria_import.serializer.shop_user:
      class: Asdoria\SyliusImportPlugin\Serializer\ShopUserSerializer
      parent: asdoria_import.serializer.abstract
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\User\ShopUser' }

    asdoria_import.serializer.address:
      parent:  asdoria_import.serializer.abstract
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Addressing\Address' }

    asdoria_import.serializer.customer_group:
      parent:  asdoria_import.serializer.abstract
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Customer\CustomerGroup' }

    asdoria_import.serializer.product_attribute:
      class: Asdoria\SyliusImportPlugin\Serializer\ProductAttributeSerializer
      parent: asdoria_import.serializer.abstract
      calls:
        - ['setDefaultLocale', ['%locale%']]
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Product\ProductAttribute' }

    asdoria_import.serializer.product_attribute_translation:
      parent:  asdoria_import.serializer.abstract
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Product\ProductAttributeTranslation' }

    asdoria_import.serializer.product:
      class: Asdoria\SyliusImportPlugin\Serializer\ProductSerializer
      parent: asdoria_import.serializer.abstract
      calls:
        - ['setDefaultLocale', ['%locale%']]
        - ['setUploader', ['@sylius.image_uploader']]
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Product\Product' }

    asdoria_import.serializer.product_translation:
      parent:  asdoria_import.serializer.abstract
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Product\ProductTranslation' }

    asdoria_import.serializer.product_attribute_value:
      class: Asdoria\SyliusImportPlugin\Serializer\ProductAttributeValueSerializer
      parent:  asdoria_import.serializer.abstract
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Product\ProductAttributeValue' }

    asdoria_import.serializer.product_image:
      parent:  asdoria_import.serializer.abstract
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Product\ProductImage' }

    asdoria_import.serializer.product_variant:
      class: Asdoria\SyliusImportPlugin\Serializer\ProductVariantSerializer
      parent:  asdoria_import.serializer.abstract
      calls:
        - ['setDefaultLocale', ['%locale%']]
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Product\ProductVariant' }

    asdoria_import.serializer.product_variant_translation:
      parent:  asdoria_import.serializer.abstract
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Product\ProductVariantTranslation' }

    asdoria_import.serializer.channel_pricing:
      parent:  asdoria_import.serializer.abstract
      tags:
        - { name: asdoria_import_serializer, type: 'App\Entity\Channel\ChannelPricing' }
