App\Entity\Customer\Customer:
    normalize: ~
    denormalize:
        company: companyName
        lastname: lastName
        firstname: firstName

App\Entity\User\ShopUser:
    priority:
        customer: ~
    normalize: ~
    denormalize:
        id_gender: gender
        lastname: lastName
        firstname: firstName
    extra_attributes:
        enabled: 1

App\Entity\Addressing\Address:
    normalize: ~
    denormalize:
        country_id: countryCode
        lastname: lastName
        firstname: firstName
        telephone: phoneNumber
    extra_attributes:
        enabled: 1

App\Entity\Product\Product:
    normalize: ~
    denormalize:
        media_gallery: images
        sku: code
        status: enabled
    extra_attributes:
        attributes: ~
        channels: ~

App\Entity\Product\ProductTranslation:
    normalize: ~
    denormalize:
        url_key: slug
        short_description: shortDescription
        meta_description: metaDescription

App\Entity\Product\ProductVariant:
    normalize: ~
    denormalize: ~
    extra_attributes:
        code: ean
        channelPricings: price
        translations: ~

App\Entity\Product\ProductAttribute:
    normalize: ~
    denormalize: ~
    extra_attributes:
        storageType: type

App\Entity\Taxonomy\Taxon:
    normalize: ~
    denormalize:
        is_active: enabled
        id: code

App\Entity\Taxonomy\TaxonTranslation:
    normalize: ~
    denormalize:
        meta_keywords: metaKeywords
        meta_title: metaDescription
        url_key: slug
