App\Entity\Customer\Customer:
    normalize: ~
    denormalize:
        company: companyName
        lastname: lastName
        firstname: firstName

App\Entity\User\ShopUser:
    priority:
        customer: ~
    normalize: ~
    denormalize:
        id_gender: gender
        lastname: lastName
        firstname: firstName
    extra_attributes:
        enabled: 1

App\Entity\Addressing\Address:
    normalize: ~
    denormalize:
        country_id: countryCode
        lastname: lastName
        firstname: firstName
        telephone: phoneNumber
    extra_attributes:
        enabled: 1

App\Entity\Product\Product:
    normalize: ~
    denormalize:
        media_gallery: images
        sku: code
        status: enabled
    extra_attributes:
        attributes: ~

App\Entity\Product\ProductAttribute:
    normalize: ~
    denormalize: ~
    extra_attributes:
        storageType: ~
